### ISSUE TITLE
Boxscore isn't working

### ISSUE THREAD

**Issue by helloitsjulian** [basketballrelativity/py_ball#5]
Hi,

I'm using the exact example that is on the documentation (and I've tried some others) but I'm not able to return anything besides a 400 or 500 error.

``# Assing a user-agent header
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36'}

game_id = '0041800001'

data = (boxscore.BoxScore(headers, game_id, endpoint='boxscoreadvancedv2', range_type='1', 
                          start_period='0', end_period='10', start_range='0', end_range='0')``

HTTPError: 500 Server Error: Internal Server Error for url: https://stats.nba.com/stats/boxscoreadvancedv2/?GameID=0041800001&RangeType=1&StartPeriod=0&EndPeriod=10&StartRange=0&EndRange=0

**Comment by basketballrelativity** [comment]
Hey, thanks for reaching out! It appears you're using an invalid GameID. If you set `game_id = '0021800001'`, the API call should work just fine (url below). Could that be the issue?

https://stats.nba.com/stats/boxscoreadvancedv2/?GameID=0021800001&RangeType=1&StartPeriod=0&EndPeriod=10&StartRange=0&EndRange=0
